### PR TITLE
Webhooks

### PR DESCRIPTION
**Pull request by nepalez**
Hi! Thank you for the gem!

While using it in a client's project, we added some missing features for webhooks and orders (following CloudPayments API).

It would be nice if you could publish a new release.

### CODE REVIEW

**Comment by undr** [comment]
@nepalez Thank you for your contribution. It's very useful contribution and I will merge it, of course. 

Only two things:
- Could you make the travis be green.
- Please, remove the stage.log file from the PR. =)

**Comment by nepalez** [comment]
Ouch! I'm sorry for this log

Concerning greenness I believe this is a temporary travis-related problem. Locally I've run specs using [wwtd](https://github.com/grosser/wwtd) for all declared environments from 1.9.3 to 2.3.0 and they pass.

I think we should wait some time - may be the problem will be solved by Travis team.

**Comment by undr** [comment]
ok. give me a while, I will check everything to be sure that nothing is broken down.

**Comment by nepalez** [comment]
As I supposed above, the problem is not with the gem, but with the new Travis platform and its "Precise builds"

That's how it works on the older one: https://travis-ci.org/nepalez/cloud_payments

**Comment by undr** [comment]
@nepalez Actually no. It has spread redness into the master

**Comment by nepalez** [comment]
Hah! I see your "no sudo" solution. Fine, thank you!
And could you please publish it to rubygems ;)

**Comment by undr** [comment]
Thanks. I just wanted to write some little help for users. I will release it tomorrow. Sorry for delay.

**Pull request merged**
